### ISSUE TITLE
[REQUEST] Make the library more versatile

### ISSUE THREAD

**Issue by adri326** [leimbernon/rust_genetic_algorithms#15]
**Is your feature request related to a problem? Please describe.**
I'm writing a compatibility layer between [my genetic algorithm crate](https://github.com/adri326/genomic-rs) and yours,
and I am noticing that you made a few decisions that heavily restrict the way your library can be used:

- `GeneT::get_id` needs to return an `&i32`, which restricts types that may implement `GeneT` to only those that contain an `i32` in them. Its presence is also not necessary in most situations, as it is only used by one crossover operator.
- `GenotypeT<Gene>` does not use an associated type, which means that a foreign type could, for instance, implement `GenotypeT<i32>` *and* `GenotypeT<MyI32Gene>`, which makes writing functions that accept a type implementing `GenotypeT` harder as their type signature needs to account for that possibility.
- `GenotypeT::get_dna` and `GenotypeT::get_dna_mut` both require the function to return a `Vec` reference, which restricts implementors to types that already contain a `Vec`
- `GenotypeT::get_fitness` and `GenotypeT::get_age` restrict the implementors to types that contain a `f32` for caching the score and types that contain a `i32` for caching the age by requiring a reference to be returned instead of a value.
- `GenotypeT::get_fitness_mut` and `GenotypeT::get_age_mut` also do, and could be replaced with a `set_fitness` and `set_age` pair of methods.

**Describe the solution you'd like**
- `GeneT::get_id`, `GenotypeT::get_fitness` and `GenotypeT::get_age` should have the reference in the output type removed
- `GeneT::get_id` is only used by one crossover operator, so making it optional would also ease the implementation of the `GeneT` trait
- `GenotypeT::get_dna` and `GenotypeT::get_dna_mut` should either return a slice or — even better — an `impl Iterator`
- `GenotypeT` should have the gene type be specified using associated types, which will ensure that only one implementation can exist at a time for a given type
- `GenotypeT::get_fitness_mut` and `GenotypeT::get_age_mut` should be replaced with `GenotypeT::set_fitness` and `GenotypeT::set_age`

I understand that making these changes would require a major version bump and would require users to change their implementation.

**Comment by leimbernon** [comment]
Good points!
Thanks for the feedback. I will work on that, in order of making my library more versatile.
Anyway, if you also want to contribute on this library, feel free :)

**Comment by adri326** [comment]
I'll happily help, I kind of burnt myself out on another project so I don't mind taking a break from it

**Comment by leimbernon** [comment]
I've made some changes on the related branch of this issue, that I think it should be enough to cover your request. If you want, I let you check it out and tell me your thoughts.
